coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "docs/"
  - "examples/"
  - "**/__pycache__/"
  - "src/**/__init__.py"
  - "src/**/py.typed"